# Python 3.8 slim 버전 사용
FROM python:3.8-slim

# 작업 디렉토리 설정
WORKDIR /src

# requirements.txt 파일 복사
COPY ./requirements.txt /src/requirements.txt

# 필요한 패키지 설치
RUN pip install --no-cache-dir --upgrade -r /src/requirements.txt
