version: '3.8'

services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_USER: cuddle
      POSTGRES_PASSWORD: cuddle12#
      POSTGRES_DB: cuddle-db
      TZ: Asia/Seoul
    ports:
      - "5432:5432"
    volumes:
      - data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: jspark6815@gmail.com
      PGADMIN_DEFAULT_PASSWORD: admin
      PGADMIN_LISTEN_PORT: 80
      TZ: Asia/Seoul
    ports:
      - "8080:80"
    depends_on:
      - postgres

  fastapi:
    build:
      context: .
      dockerfile: DockerFile
    ports:
      - "8000:80"
    volumes:
      - ./app:/src/app
    depends_on:
      - postgres
    environment:
      ENV: PROD
      TZ: Asia/Seoul

volumes:
  data:
    driver: local
