# Python 3.8 slim 버전 사용
FROM python:3.8-slim

# 작업 디렉토리 설정
WORKDIR /src

# requirements.txt 파일 복사
COPY ./requirements.txt /src/requirements.txt

# 필요한 패키지 설치
RUN pip install --no-cache-dir --upgrade -r /src/requirements.txt

COPY ./.env /src/.env

# 애플리케이션 코드 복사
COPY ./app /src/app

WORKDIR /src/app

# Uvicorn으로 애플리케이션 실행
CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]

HEALTHCHECK CMD curl --fail http://localhost:8000/health || exit 1